postgresql:
    auth:
        password: ENC[AES256_GCM,data:DaLMSL4Lpu91NI36rGTgTSxCcAm5YroG2nnjxhZN8L8=,iv:QbToLD+jYILiLozupX2U9wY2CRucbyeKOAWTGxozOMY=,tag:cUUkBBLDn9h9H34w+DoY8A==,type:str]
        postgresPassword: ENC[AES256_GCM,data:Y2pgsfkf+1TpkXHpMPap+BVHaJ0dFe7I1H4J1DpMM+o=,iv:UUGC5DGjaiQt2s0Ef8l0eUIMrOHI9vH3WCdgDIyzbzY=,tag:nkiDjnfYiizvIm6lu5Gyfw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:908027387380:key/04b220a8-3f31-476f-a61f-cb5c9feda34c
          created_at: "2024-11-04T09:20:40Z"
          enc: AQICAHhNz+TyKd6cO40RqoEZxEDQk5iG8gyAAcA9dkJCd/PAggFqRnC1CBAMD+6cqf4LvRg5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1YEosdQk8aPRvLKBAgEQgDu7HLxY7/k1y9iawFMtfW0uBi0fdmnOIl9EVshpkksCdXls+wkSr5XG9xd0PxeVOW6iTtQekNVOeYgvNA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-04T09:25:48Z"
    mac: ENC[AES256_GCM,data:vYd8aNM39S8Ex6Me1EzXbRhww03qfsDl5HhoPgsMaRk7k6R5sI64trYDoGL+ELksu5RRyLKmYm02kqIix3/fzTSLEpvEQyHKmDMmGwF5fT+WQNAlpxuRgElaozQDuOvjvv/imSXrnojN/5vJCeLSBhncRRFvjrL758n8JGhJxqo=,iv:vNzMi5LmdJx4d4FqdX6wcukcyzaBrzyWixqjx0mMyOg=,tag:zwKCC+wkFUQvqr3C82iyhw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
