postgresql:
    auth:
        password: ENC[AES256_GCM,data:x/JOIb1MOPNCvKELng==,iv:mIOz5tCXnNgdj7VAwnoRR1/zcj+wz0pa2xGal7Miq0A=,tag:mN0NCmxy6ln9FgAZxmd+MQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-northeast-1:908027387380:key/04b220a8-3f31-476f-a61f-cb5c9feda34c
          created_at: "2024-11-04T09:20:40Z"
          enc: AQICAHhNz+TyKd6cO40RqoEZxEDQk5iG8gyAAcA9dkJCd/PAggFqRnC1CBAMD+6cqf4LvRg5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1YEosdQk8aPRvLKBAgEQgDu7HLxY7/k1y9iawFMtfW0uBi0fdmnOIl9EVshpkksCdXls+wkSr5XG9xd0PxeVOW6iTtQekNVOeYgvNA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-04T11:20:10Z"
    mac: ENC[AES256_GCM,data:APiYqBM8DU11b4Qx5ocCyb7B71aVZe/XCaZfRXntuGz5TWSvLlGHrDl3hN6BLN/LfTmoqlltuzwRWfmF0w2kjKhutB53bcJMwrXenCWxIpTfHd11BSgUegXphHAoPDcivATN7hoQjYjTvSuQyYrV65im0NS5+sr1j/8wEE4DMAA=,iv:sAiVcYypv9Ax94ZPczGVU/SvfbvkaVwukKlxSRu+7nU=,tag:d3JxMLnUkiMm55ONuYD7uw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
