environments:
  {{ .Environment.Name }}:

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: prometheus
    createNamespace: true
    chart: prometheus-community/kube-prometheus-stack
    version: 65.2.0
    atomic: true
    values:
      - common/values.yaml
      - "{{ .Environment.Name }}/values.yaml"
