environments:
  {{ .Environment.Name }}:

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: unguard
    url: ghcr.io/dynatrace-oss/unguard/chart
    oci: true

releases:
  ## https://github.com/bitnami/charts/tree/mariadb/11.5.7/bitnami/mariadb
  - name: unguard-db
    namespace: unguard
    createNamespace: true
    chart: bitnami/mariadb
    version: 11.5.7
    atomic: true
    values:
      - common/mariadb.values.yaml
    secrets:
      - "{{ .Environment.Name }}/mariadb.secrets.yaml"
  ## https://github.com/dynatrace-oss/unguard/tree/v0.9.3/chart
  - name: unguard
    namespace: unguard
    createNamespace: false
    chart: unguard/unguard
    version: 0.9.3
    atomic: true
    secrets:
      - "{{ .Environment.Name }}/unguard.secrets.yaml"
    strategicMergePatches:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: unguard-like-service
        spec:
          template:
            spec:
              containers:
                - name: like-service
                  env:
                    - name: DB_HOST
                      value: unguard-db-mariadb
                    - name: DB_PORT
                      value: "3306"
