environments:
  {{ .Environment.Name }}:

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  ## https://github.com/bitnami/charts/tree/mariadb/11.5.7/bitnami/mariadb
  - name: unguard-db
    namespace: unguard
    createNamespace: true
    chart: unguard-mariadb bitnami/mariadb
    version: 11.5.7
    atomic: true
    values:
      - common/mariadb.values.yaml
    secrets:
      - "{{ .Environment.Name }}/mariadb.secrets.yaml"
